### PR TITLE
Fix muting groups

### LINKED ISSUE #649: [BUG] 'Mute' option for groups does not work
### Description

The option to 'Mute'a group (stop receiving notifications for messages in that specific group) appears in the interface, but does not work.

### Steps to Reproduce

1. Use Axolotl, be in a group
2. When viewing the group, open the Settings menu. The Mute option appears (as the only settable option)
3. Tap the setting. Longpress the setting. Do whatever you want to the setting, it will not change.

**Expected behavior:** The setting gets changed, and messages in that group no longer trigger a notification

**Actual behavior:** There is no visual change and notifications keep arriving

#### Versions

Axolotl 1.0.8

#### Device

Ubuntu Touch on Sony Xperia X

#### Link to Debug Log
I'll provide this if it seems useful in this case. It's kind of a pain. I would have to know how to copy the useful part, I don't know what that is.

### PR DESCRIPTION
**Pull request by Blackoverflow**
Fixes #649

A typo broke this functionality.

Muting / unmuting works, but the chat isn't updated, so it looks like it didn't work until I leave the group.

### CODE REVIEW

**Comment by Blackoverflow** [comment]
Changelog proposal: Fix option to mute groups (blackoverflow)

**Comment by Blackoverflow** [comment]
If I enter or mute/unmute an group, the following error is logged:
`[axolotl] sendCurrentChat: groups unknown group ID 58d7934d<redacted>`
`textsecure.GetGroupById(s.Tel)`  seems to be wrong. But changing it to `textsecure.GetGroupById(s.UUID) ` did not change the behaviour.
https://github.com/nanu-c/axolotl/blob/fa9f0ec4af624659e13dab03df025e3294e895bf/app/webserver/helpers.go#L63-L68
@nanu-c or someone else, do you understand whats wrong and can help me?

File: app/webserver/helpers.go [hunk 1]
```diff
@@ -89,7 +89,7 @@ func updateCurrentChat(s *store.Session) {
 		c   *textsecureContacts.Contact
 	)
 	if s.IsGroup {
-		gr, err = textsecure.GetGroupById(s.Tel)
+		gr, err = textsecure.GetGroupById(s.UUID)
```
Comment (nanu-c) [inline app/webserver/helpers.go:92]: I think we should use the `store.GetGroupById` instead of querying the backend: https://pkg.go.dev/github.com/nanu-c/axolotl@v1.0.8/app/store#GetGroupById

Comment (Blackoverflow) [reply app/webserver/helpers.go]: will try it.

Comment (Blackoverflow) [reply app/webserver/helpers.go]: Using store.GetGroupById worked.

Unfortunately it introduced the regression that Axolotl leaves conversations that are not groups after I open them.
I'll see what I can do about that.

**Comment by Blackoverflow** [comment]
Entering non group chats works again, but the message list stays empty.

**Comment by Blackoverflow** [comment]
Finally, it works! @nanu-c do you want to review?

**Comment by Blackoverflow** [comment]
I tried myself at writing unit tests for it, but there are some obstacles with that. I'll make a new branch for that.

File: app/store/session.go [hunk 2]
```diff
@@ -257,7 +257,7 @@ func (s *Session) ToggleSessionNotifcation() {
 
 	}
 	//qml.Changed(s, &s.Notification)
```
Comment (nanu-c) [inline app/store/session.go:259]: this lines `qml.Changed(` can be removed whenever you stumble upon them.

File: app/webserver/messages.go [hunk 3]
```diff
@@ -21,18 +21,23 @@ type ContactListEnvelope struct {
 type DeviceListEnvelope struct {
 	DeviceList []textsecure.DeviceInfo
 }
+type Group struct {
```
Comment (nanu-c) [inline app/webserver/messages.go:24]: This all looks really good to me. Only question is, why to you use a new type instead of recycling `store.GroupRecord` ? If it's because of the database field type i would prefer if the type still resides in `store`.

File: axolotl-web/src/store/store.js [hunk 4]
```diff
@@ -410,14 +410,14 @@ export default createStore({
         app.config.globalProperties.$socket.send(JSON.stringify(message))
       }
     },
-    openChat(state, chatId) {
-      this.commit("CLEAR_MESSAGELIST");
```
Comment (nanu-c) [inline axolotl-web/src/store/store.js:414]: If we remove that, we need good testing because I don't remember exactly why I put it there, but it was for a reason. So let's add it to a testing list for the next release.

File: app/webserver/messages.go (hunk 3 above)
Comment (Blackoverflow) [reply app/webserver/messages.go:24]: I prefer separating definitions for different tasks. GroupRecord is the database representation, not the API representation.
Using GroupRecord, I would have to change the JavaScript code, because the Members are one String instead of a String list in GroupRecord.

Its not sensible to adjust JavaScript code, because of database restrains.

File: axolotl-web/src/store/store.js (hunk 4 above)
Comment (Blackoverflow) [reply axolotl-web/src/store/store.js:414]: Without this change, I had a bug that the message lists were not loaded.
Before, MessageList.vue dispatched "openChat" and directly after that "getMessageList".
Both of them commited "CLEAR_MESSAGELIST".

I changed "openChat" to dispatch a "getMessageList" and removed one "CLEAR_MESSAGELIST", since once should be enough. Of cause, I'm not entirely sure this won't break anything, but it looked good when I tried it on my phone.

**Review by nanu-c — APPROVED** [review]
